### ISSUE TITLE
Default/forced filter?

### ISSUE THREAD

**Issue by Ancyker** [flat3/lodata#260]
Is there a way to enforce a sort of "default" filter? Basically, there is data in the table that should never show on the API. Think of it like there is a `Status` field and data should only ever show when `Status` is `Active` and it should never show otherwise.

**Comment by 27pchrisl** [comment]
Yes, there are two ways:

You could subclass your current `Model` and apply a global scope in the subclass. Then pass this subclass when doing discovery instead of the original model. The downside of this one is your need to override the name of the table so it's not taken from the subclass name.

Alternatively you could subclass `EloquentEntitySet` and override the [`getBuilder`](https://github.com/flat3/lodata/blob/06919379148727da41d149122c98c11692a3e2cd/src/Drivers/EloquentEntitySet.php#L490) method to return a builder instance that has a model local scope applied. You can apply any builder filter at this point instead of using a local scope. You can then use your new `CustomEloquentEntitySet` in discovery as `(new CustomEloquentEntitySet(MyModel::class))->discovery()`

**Comment by 27pchrisl** [comment]
@Ancyker would you mind letting me know which of the two methods worked for your application, or if you made a different method work better so I can put this into the documentation?
