### ISSUE TITLE
Operations and discovering

### ISSUE THREAD

**Issue by Iseldore** [flat3/lodata#274]
Hi,

I'm in trouble with discovering and operations. I'm on the last version.

Here is what I have : 

```<?php
// First class
class User extends Model {
	#[LodataRelationship]
	public function orders() {
		return $this->hasMany(Order::class);
	}
	
	#[LodataFunction(return: "array")]
	public function function1(string $param){
		...
	}
}

// Second class
class Order extends Model {
	#[LodataRelationship]
	public function user() {
		return $this->belongsTo(User::class);
	}
	
	#[LodataFunction(return: "array")]
	public function function2(string $param){
		...
	}
}

// Discovering
\Lodata::discover(\App\Models\User::class);
```

The function1 is working, but the function2 is not (`No route handler was able to process this request`)

If I change discovering for : 
```
\Lodata::discover(\App\Models\Order::class);
\Lodata::discover(\App\Models\User::class);
```

Then the function2 is working but not function1.

Any idea?
Thanks!

**Comment by 27pchrisl** [comment]
Hi @Iseldore, this was a problem relating to how discovery worked with relationships and operations. Discovering one of your models would trigger discovery on the other (as they are related), but only the first discovery checked operations. In your example where you ran "discover" on both, the second was actually ignored because `User` was already discovered by `Order`.

Fixed in https://github.com/flat3/lodata/releases/tag/v5.17.0
