### ISSUE TITLE
primary key type string despite using numeric id

### ISSUE THREAD

**Issue by Remo** [flat3/lodata#45]
I just discovered lodata, currently playing around to see if it's an alternative for our own implementation. It looks pretty great at first glance, thanks for sharing it!

My demo project has a simple model:
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{   
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'product_name',
        'price',
    ];
}
```

I can query it by using `/odata/Products`, great. I then wanted to query a single record, I tried `/odata/Products(1)`, no luck, it fails with:
```
{"code":"invalid_identifier_value","message":"The type of the provided identifier value was not valid for this entity type","details":">1<"}
```

I did some digging and it seems like it's detected as a string. I tried to define `keyType`, but not luck. Same for `$casts`:
```php
    protected $casts = [
        'id' => 'integer',
    ];
```

As soon as I've changed it to a string, it worked `/odata/Products(id='1')` or `/odata/Products('1')`.

Is there something I missed that allows me to define the data type of properties?

**Comment by 27pchrisl** [comment]
Hi @Remo !

You **can** override it, but the fact Lodata got the type wrong during discovery is a bug (assuming the in-database sql type of the id column really is a string? otherwise it's a different issue).

I've patched this in #46, will release that shortly. The issue was that Lodata observed the Laravel casts for all columns _except_ the primary key. Now it does it for the key as well.

For info as well it is possible to override property types after discovery, the way to do that would have been:

```
\Lodata::getEntityType('Product')->setKey(new \Flat3\Lodata\DeclaredProperty('id', \Flat3\Lodata\Type::string()));
```

Which gets the discovered entity type using the model name, adds a new declared property which would overwrite the existing discovered one as it has the same identifier, and sets it as the key.

**Comment by 27pchrisl** [comment]
Reopened for confirmation issue is resolved

**Comment by Remo** [comment]
Wow you're quick, thanks!

The change does the trick, `$casts` and `$keyType` are working now and the in-database type is also correctly determined.
