### ISSUE TITLE
odata prefix

### ISSUE THREAD

**Issue by thinkerytim** [flat3/lodata#500]
I'm using lodata with the syncfusion react components. It seems that the syncfusion components expect all the response metadata to be prefixed with `odata`, and this is causing their components to fail to correctly parse the returned data.

For example, my user data returned by my lodata endpoint looks like this: 

```
{
	"@context": "http://localhost/odata/$metadata#Users",
	"value": [
		{userdata here}
	],
	"@count": 19,
	"@nextLink": "http://localhost/odata/Users?%24count=true&top=12&skip=12"
}
```

Syncfusion expects the `@context`, `@count` and `@nextlink` to read `@odata.context`, `@odata.count`, `@odata.nextlink` etc. 
Is this an optional part of the odata spec, or is there a way I can make lodata return these items with this prefix?

**Comment by 27pchrisl** [comment]
Hi @thinkerytim, this is likely because syncfusion supports OData v4.0, but not v4.01 (which dropped the extra `odata.`). You can either handle this client-side by adding the `OData-Version: 4.0` header to every request, so Lodata will drop into that version mode, or you can make Lodata use 4.0 by default if unspecified by the client, by changing `config/lodata.php`.

More info on how this is handled for devextreme here: https://lodata.io/clients/devextreme.html

**Comment by thinkerytim** [comment]
Thanks for the quick help-- setting the lodata config to version `4.0` resolved the issue. Great work on this package!
