### ISSUE TITLE
dynamic columns in select and orderby

### ISSUE THREAD

**Issue by Remo** [flat3/lodata#58]
I'm trying to reproduce some of our hacky stuff we did during the last few months. I'm fully aware that some of it won't win us a price for elegant code, but business applications sometimes have ugly requirements.

---

While I do like to offload stuff to the database, sometimes we have to inject things with the help of some PHP code. I was able to add a "virtual" column by using this:

```php
protected $appends = ['random_sort'];

public function getRandomSortAttribute()
{
    return 123;
}
```

This was not immedatiely visible, but that I could easily fix by adding the last line in this snippet:

```php
\Lodata::discoverEloquentModel(\App\Models\Product::class)->discoverRelationship('descriptions');

$productType = \Lodata::getEntityType('Product');
$productType->addProperty((new DeclaredProperty('random_sort', Type::decimal())));
```

Great!

---

Step 2, sort by a virtual column.

```/odata/Products?$orderby=random_sort```

No luck, tries to do an SQL sort. I attempted to add it to the SQL query by adding some code to the product model:

```php
protected static function boot()
{
    parent::boot();

    static::addGlobalScope('random_sort', function (Builder $builder) {
        $builder->select('*')->addSelect(\DB::raw('rand() AS random_sort'));
    });
}
```

No luck, column value doesn't show up. It does when I'm using tinker to fetch a record from the database though.

We have a surprising number of situations where we want to sort by a value that isn't found in a column. Not long ago we calculated the distance to the current location by using this https://stackoverflow.com/questions/35467774/haversine-and-laravel

Not sure how I would be able to replicate this using lodata, but maybe it's another case (in addition to this https://github.com/flat3/lodata/issues/49#issuecomment-805745207) where an event would allow me to inject some column before the query is executed? An event before and after a command is executed would probably help a lot to do ugly things ;-)

**Comment by 27pchrisl** [comment]
@Remo If you want to modify the entity set before it's sent back to the client in PHP (post-query), then the best odata technique might be to create a function that the entity set is piped through. I created an example in tests to show this with a function that performs a sort using a column name you pass in as a function argument, but you can manipulate the entities in any way you like including add/deleting/modifying them with a function.

https://github.com/flat3/lodata/blob/d383083eb084f9f3cc6c0b0c29a36f0fc1b45fe4/tests/Unit/Operation/FunctionTest.php#L249

If you want to modify the SQL that's being sent that generates the entity set, then the best approach might be to subclass EloquentEntitySet (or SQLEntitySet) and override methods relating to the query.

Note that you could also use these two methods together. Because the SQL query is not run until the data is emitted, you can create override methods in your subclassed entity set to modify the query, call these methods as part of an odata Function, then return the modified entity set from the function and the SQL query will be called at the point the data is emitted.

**Comment by Remo** [comment]
That's really slick. I guess I have to have a closer look at the way you allow custom functions to be added to entities 😃
