### ISSUE TITLE
setAlternativeKey

### ISSUE THREAD

**Issue by kristalis** [flat3/lodata#85]
thanks for the pkg.   Can I get help on how and where to setup the alternative key in my laravel app.  
Also how do you paginate big data request

**Comment by 27pchrisl** [comment]
Hi, did the instructions at https://github.com/flat3/lodata#alternative-keys work for you? A good place for this code would be in a Laravel service provider.

For pagination, you can see the `$top` and `$skip` documentation: https://docs.oasis-open.org/odata/odata/v4.01/os/part1-protocol/odata-v4.01-os-part1-protocol.html#sec_SystemQueryOptiontop

**Comment by kristalis** [comment]
> Hi, did the instructions at https://github.com/flat3/lodata#alternative-keys work for you? A good place for this code would be in a Laravel service provider.
thanks I saw that but new to laravel so not getting it to work.  I added it under boot() but it is spitting out some errors
**_Call to a member function getProperty() on null_**

**Comment by 27pchrisl** [comment]
Yup the `boot` method should work. Probably you specified an entity type name that did not exist. Did you use the `discoverEloquentModel` technique? If so the entity type will have the same name as the model, with the same capitalization (ie `Flight` instead of `flight`). If that's not it can you paste a more complete code sample?

**Comment by kristalis** [comment]
Thanks i used the table name instead of model.  odata is quite neat.  I have a few rows related to the alternativekey but it only displays one row.  
Without odata I was using groupby to get the rows associated with the alternativekey, how do i translate that with the odata

**Comment by 27pchrisl** [comment]
The alternative key is intended to use instead of an ID, so it can only return a single row. If you wanted to get all rows that matched a particular field you'd use a filter like `http://example.com/odata/Flights?$filter=altkeyfield eq 4`. You can use `$select` (https://docs.oasis-open.org/odata/odata/v4.01/os/part1-protocol/odata-v4.01-os-part1-protocol.html#_Toc31358942) to return specific fields.

**Comment by kristalis** [comment]
oh wow, thanks.  This is quite cool.

**Comment by 27pchrisl** [comment]
@kristalis thanks! If you have any other questions you can open a new issue
