### ISSUE TITLE
how to get GUID into my odata

### ISSUE THREAD

**Issue by kristalis** [flat3/lodata#92]
Hi guys, this pkg from Chris is quite neat and trying to explore every angle.  My demo is using mysql and I require the odata to have a GUID which I understand can't be generated into mysql db.
Is there a work around this to get GUID for the id in the schema?
Can the Type be set dynamically?

**Comment by 27pchrisl** [comment]
Yes, you can set the type of the key field. If you have an entity type `airport` you can do:

```php
\Lodata::getEntityType('airport')->setKey(new \Flat3\Lodata\DeclaredProperty('id', \Flat3\Lodata\Type::guid()));
```
Which would get that entity type, and then overwrite the key with a new property declaration of that type.

You can then request an entity like:
```
http://localhost:8000/odata/airports(B833C653-4A06-437F-B963-8C8D5FFA29C9)
```

GUIDs will also be property encoded in the entity JSON objects.

While checking this worked properly I did find an issue where Lodata did make a rough assumption that the primary key field of an SQL table would be numeric during insert operations, so in the current release you cannot create entities that have a GUID id. This will be fixed in the upcoming version.

**Comment by kristalis** [comment]
Thanks it is set perfectly.    With regards to the id failing, I created a uuid during the insert
$id = Str::uuid()->toString();
